<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="pi" params="3.141592653589793" />

  <xacro:macro name="base_link" params="suffix height *joint_origin">
    <link name="base_${suffix}_link" >
      <collision>
        <origin xyz="0 0 ${-height/2}" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 ${height}" />
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 ${-height/2}" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 ${height}" />
        </geometry>
        <material name="Black" >
          <color rgba="0 0 0 1." />
        </material>
      </visual>
      <inertial>
        <origin xyz="0 0 ${-height/2}" rpy="0 0 0"/>
        <mass value="100.0"/>
        <inertia ixx="${(0.1*0.1 + height*height)*100.0/3}" iyy="${(0.1*0.1 + height*height)*100.0/3}" izz="${(0.1*0.1*2)*100.0/3}" ixy="0" ixz="0" iyz="0" />
      </inertial>
    </link>
    <joint name="fixed_${suffix}" type="fixed">
      <parent link="world"/>
      <child link="base_${suffix}_link"/>
      <xacro:insert_block name="joint_origin" />
    </joint>
  </xacro:macro>
</robot>

