samplebot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_joint
