joint_limits:
  wheel_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    min_velocity: -6
    max_velocity: 6
    has_acceleration_limits: true
    min_acceleration: -1
    max_acceleration: 1
