joint_limits:
  cylinder_1_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    min_velocity: -5
    max_velocity: 5
    has_acceleration_limits: true
    min_acceleration: -10
    max_acceleration: 10

  cylinder_2_joint:
    has_position_limits: true
    min_position: -1.0
    max_position: 0.0
    has_velocity_limits: true
    min_velocity: -5
    max_velocity: 5
    has_acceleration_limits: true
    min_acceleration: -10
    max_acceleration: 10

  cylinder_3_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    min_velocity: -1
    max_velocity: 1
    has_acceleration_limits: true
    min_acceleration: -10
    max_acceleration: 10

  cylinder_4_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    min_velocity: -5
    max_velocity: 5
    has_acceleration_limits: true
    min_acceleration: -10
    max_acceleration: 10

